### PR TITLE
Remove mistyped character.

### PR DESCRIPTION
**Pull request by pavel-d**
Please merge it ASAP.

Thanks

opscode-cookbooks/openssl#19

### CODE REVIEW

**Comment by jujugrrr** [comment]
:+1: :shipit: . Maybe we could add a test for the Lib as well

**Comment by olarth** [comment]
+1

**Comment by olarth** [comment]
:+1:

**Comment by BrianEWhipple** [comment]
Something in your release process is broken.  +1 to adding tests.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @pavel-d

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Pull request merged**
